# Generated by Django 2.1.1 on 2018-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustedQueryCase', models.CharField(blank=True, max_length=200, null=True)),
                ('NewSemanticTypeName', models.CharField(blank=True, max_length=100, null=True)),
                ('preferredTerm', models.CharField(blank=True, max_length=200, null=True)),
                ('FuzzyToken', models.CharField(blank=True, max_length=50, null=True)),
                ('SemanticTypeName', models.CharField(blank=True, max_length=100, null=True)),
                ('SemanticGroup', models.CharField(blank=True, max_length=50, null=True)),
                ('timesSearched', models.IntegerField(null=True)),
                ('FuzzyScore', models.IntegerField(null=True)),
                ('Modified', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'manual_assignments',
            },
        ),
    ]
